version: "3.9"

services:
  db:
    image: postgres
    restart: always
    ports:
      - 5433:5432
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: s3cret
      POSTGRES_DB: phonebook

volumes:
  pg_data:
