version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3009:3009
    env_file: .env
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    ports:
      - 5433:5432
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: s3cret
      POSTGRES_DB: phonebook

  adminer:
    image: adminer
    restart: always
    ports:
      - 8085:8080
    environment:
      ADMINER_DEFAULT_SERVER: db
    depends_on:
      - db

volumes:
  pg_data:
