openapi: 3.0.0
info:
  title: PhoneBook API - OpenAPI 3.0
  contact:
    email: paulamurta@hotmail.com
  version: 1.0.0
servers:
  - url: https://localhost:3009
tags:
  - name: Auth
    description: Auth related routes
  - name: User
    description: User related routes
  - name: Contact
    description: Contacts related routes
  - name: Group
    description: Groups related routes
paths:
  /auth/auth/login:
    post:
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoginRequest"
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LoginResponse"
        "401":
          description: In case of invalid credentials
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "500":
          description: Any other error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
  schemas:
    ErrorResponse:
      type: object
      properties:
        message:
          type: string
          description: Error message
    LoginRequest:
      type: object
      properties:
        email:
          type: string
          format: email
        password:
          type: string
          minLength: 4
          format: password
    LoginResponse:
      type: object
      properties:
        accessToken:
          type: string
          description: Access token to be used on the application
